# Generated by Django 4.2.7 on 2026-05-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DetectRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("crowd_count", models.IntegerField()),
                ("density_level", models.CharField(max_length=50)),
                ("is_abnormal", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "detect_record",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="TrainLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("epoch", models.IntegerField()),
                ("loss", models.FloatField()),
                ("mae", models.FloatField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "train_log",
            },
        ),
    ]
