# Generated by Django 6.0.5 on 2026-05-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="用户消息")),
                ("reply", models.TextField(verbose_name="AI回复")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="对话时间"),
                ),
            ],
            options={
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="DetectRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("crowd_count", models.IntegerField()),
                ("density_level", models.CharField(max_length=50)),
                ("is_abnormal", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("is_video", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "detect_record",
                "ordering": ["-create_time"],
            },
        ),
    ]
