# Generated by Django 6.0.5 on 2026-06-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="detectrecord",
            options={"ordering": ["-create_time"], "verbose_name": "检测记录"},
        ),
        migrations.RemoveField(
            model_name="detectrecord",
            name="crowd_count",
        ),
        migrations.RemoveField(
            model_name="detectrecord",
            name="density_level",
        ),
        migrations.RemoveField(
            model_name="detectrecord",
            name="is_video",
        ),
        migrations.AddField(
            model_name="detectrecord",
            name="class_data",
            field=models.JSONField(blank=True, default=dict, verbose_name="类别统计明细"),
        ),
        migrations.AddField(
            model_name="detectrecord",
            name="density_value",
            field=models.FloatField(default=0.0, verbose_name="密度(个/m²)"),
        ),
        migrations.AddField(
            model_name="detectrecord",
            name="total_count",
            field=models.IntegerField(default=0, verbose_name="目标总数"),
        ),
        migrations.AlterField(
            model_name="detectrecord",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="检测时间"),
        ),
        migrations.AlterField(
            model_name="detectrecord",
            name="file_path",
            field=models.CharField(max_length=500, verbose_name="结果图路径"),
        ),
        migrations.AlterField(
            model_name="detectrecord",
            name="filename",
            field=models.CharField(max_length=255, verbose_name="文件名"),
        ),
        migrations.AlterField(
            model_name="detectrecord",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="detectrecord",
            name="is_abnormal",
            field=models.BooleanField(default=False, verbose_name="是否密度异常"),
        ),
        migrations.AlterModelTable(
            name="detectrecord",
            table="detection_records",
        ),
    ]
