# Generated by Django 4.2.7 on 2026-05-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="用户消息")),
                ("reply", models.TextField(verbose_name="AI回复")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="对话时间"),
                ),
            ],
            options={
                "ordering": ["-create_time"],
            },
        ),
    ]
