# Generated by Django 4.2.7 on 2026-05-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_chatrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectrecord",
            name="is_video",
            field=models.BooleanField(default=False),
        ),
    ]
